version: '3.9'

volumes:
  postgres:
    name: "postgres-rocket"

networks:
  app:
    name: "rocket"

services:
  postgres:
    image: postgres:16
    restart: always
    hostname: "postgres-srv"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1Gb"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      app:

  adminer:
    image: adminer:4.8.1
    restart: always
    hostname: adminer-srv
    environment:
      ADMINER_DEFAULT_SERVER: postgres-srv
    deploy:
      resources:
        limits:
          memory: '128Mb'
          cpus: '0.05'
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      app:
